replicaCount: 1

image:
  repository: astraluniverse/bank-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  nodePort: 32172

mysql:
  enabled: true
  image: "mysql:8.0"
  database: bank
  user: bankuser
  password: demo-bank-password
  rootPassword: demo-root-password
  storage:
    size: 2Gi
    storageClassName: ""   # leave empty to use cluster default
